# Generated by Django 3.2.9 on 2021-12-16 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_booked',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
