# Generated by Django 3.2.9 on 2021-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.IntegerField()),
                ('room_name', models.CharField(max_length=50)),
                ('room_num', models.IntegerField()),
                ('price', models.IntegerField()),
                ('min_person', models.IntegerField()),
                ('max_person', models.IntegerField()),
                ('detail', models.TextField(blank=True)),
                ('pic1', models.URLField()),
                ('pic2', models.URLField()),
                ('pic3', models.URLField()),
                ('isFree', models.BooleanField(default=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('type_name', models.CharField(max_length=20)),
                ('room_free', models.IntegerField()),
                ('rating', models.FloatField()),
                ('pic1', models.URLField()),
                ('pic2', models.URLField()),
                ('pic3', models.URLField()),
            ],
        ),
    ]
