# Generated by Django 3.2.9 on 2021-12-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pic1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='pic2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='pic3',
            field=models.CharField(max_length=100),
        ),
    ]
